### PR TITLE
An admin can now change the prof and the number of peer teachers desired for a section

### LINKED ISSUE #92: Course Section Customization
It is important that course sections can be changed to allow more or fewer Peer Teachers. This is a field in the database. The plan is to add a fullscreen modal on the Admin page that displays each section and allows for sections to be added, deleted, and updated with an emphasis on updating the capacity of Peer Teachers.

Work will be done by @benbeauchamp7 for the frontend modal with @pulchroxloom creating API endpoints and lambdas as necessary.

### PR DESCRIPTION
**Pull request by benbeauchamp7**
Use the "edit course sections" button and click on blocks to update them, then click "save updated sections" to upload them. The changes will persist.

### CODE REVIEW

**Comment by benbeauchamp7** [comment]
It's important to note that sections are not tied together in the interface, but are logically. Editing one section of 110-505 will not cause the other section to update until the updated sections are saved. This is the case because getting the blocks to update together would be complicated.

**Review by dantebarbieri — APPROVED** [review]
Lgtm

**Comment by benbeauchamp7** [comment]
Closes #94

**Comment by dantebarbieri** [comment]
Works and lgtm
Shame the blocks aren't linked but cest la vie

**Pull request merged**
